//! Tree-sitter-based Rust symbol extraction for codebase search.

use serde::{Deserialize, Serialize};
use std::path::Path;

use crate::error::StoreError;

/// Kind of code symbol extracted from a Rust source file.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum SymbolKind {
    Function,
    Struct,
    Enum,
    Trait,
    Impl,
    Const,
    Static,
    TypeAlias,
    Macro,
    Module,
}

impl SymbolKind {
    pub fn as_str(self) -> &'static str {
        match self {
            SymbolKind::Function => "function",
            SymbolKind::Struct => "struct",
            SymbolKind::Enum => "enum",
            SymbolKind::Trait => "trait",
            SymbolKind::Impl => "impl",
            SymbolKind::Const => "const",
            SymbolKind::Static => "static",
            SymbolKind::TypeAlias => "type_alias",
            SymbolKind::Macro => "macro",
            SymbolKind::Module => "module",
        }
    }

    pub fn from_kind_str(s: &str) -> Option<Self> {
        match s {
            "function" => Some(SymbolKind::Function),
            "struct" => Some(SymbolKind::Struct),
            "enum" => Some(SymbolKind::Enum),
            "trait" => Some(SymbolKind::Trait),
            "impl" => Some(SymbolKind::Impl),
            "const" => Some(SymbolKind::Const),
            "static" => Some(SymbolKind::Static),
            "type_alias" => Some(SymbolKind::TypeAlias),
            "macro" => Some(SymbolKind::Macro),
            "module" => Some(SymbolKind::Module),
            _ => None,
        }
    }
}

/// A code symbol extracted from a Rust source file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Symbol {
    pub name: String,
    pub file_path: String,
    pub line: u32,
    pub end_line: u32,
    pub kind: SymbolKind,
    pub signature: Option<String>,
    /// For methods: the name of the enclosing impl type.
    pub parent: Option<String>,
}

/// Extract all symbols from a Rust source string.
pub fn extract_symbols(source: &str, file_path: &str) -> Vec<Symbol> {
    let mut parser = tree_sitter::Parser::new();
    // SAFETY: tree_sitter_rust::LANGUAGE is a valid Language generated by tree-sitter-rust.
    parser
        .set_language(&tree_sitter_rust::LANGUAGE.into())
        .expect("failed to load Rust grammar — version mismatch?");

    let tree = match parser.parse(source, None) {
        Some(t) => t,
        None => return Vec::new(),
    };

    let mut symbols = Vec::new();
    let source_bytes = source.as_bytes();
    walk_node(
        tree.root_node(),
        source_bytes,
        file_path,
        None,
        &mut symbols,
    );
    symbols
}

/// Extract all symbols from a Rust source file on disk.
pub fn extract_symbols_from_file(path: &Path) -> Result<Vec<Symbol>, StoreError> {
    let source = std::fs::read_to_string(path)?;
    let file_path = path.to_string_lossy().to_string();
    Ok(extract_symbols(&source, &file_path))
}

fn walk_node(
    node: tree_sitter::Node<'_>,
    source: &[u8],
    file_path: &str,
    parent: Option<&str>,
    symbols: &mut Vec<Symbol>,
) {
    let kind = node.kind();

    let symbol_kind = match kind {
        "function_item" => Some(SymbolKind::Function),
        "struct_item" => Some(SymbolKind::Struct),
        "enum_item" => Some(SymbolKind::Enum),
        "trait_item" => Some(SymbolKind::Trait),
        "impl_item" => Some(SymbolKind::Impl),
        "const_item" => Some(SymbolKind::Const),
        "static_item" => Some(SymbolKind::Static),
        "type_alias" => Some(SymbolKind::TypeAlias),
        "macro_definition" => Some(SymbolKind::Macro),
        "mod_item" => Some(SymbolKind::Module),
        _ => None,
    };

    if let Some(sym_kind) = symbol_kind {
        let name = node
            .child_by_field_name("name")
            .and_then(|n| n.utf8_text(source).ok())
            .unwrap_or("<unnamed>")
            .to_string();

        let start_line = node.start_position().row as u32 + 1;
        let end_line = node.end_position().row as u32 + 1;

        // For impl blocks, extract the impl target type to use as parent for methods.
        let impl_type_name: Option<String> = if sym_kind == SymbolKind::Impl {
            node.child_by_field_name("type")
                .and_then(|n| n.utf8_text(source).ok())
                .map(String::from)
        } else {
            None
        };

        symbols.push(Symbol {
            name: name.clone(),
            file_path: file_path.to_string(),
            line: start_line,
            end_line,
            kind: sym_kind,
            signature: None,
            parent: parent.map(String::from),
        });

        // For impl blocks, walk children with the impl target type as parent.
        if sym_kind == SymbolKind::Impl {
            let child_parent = impl_type_name.as_deref().unwrap_or(&name);
            for i in 0..node.child_count() {
                if let Some(child) = node.child(i) {
                    walk_node(child, source, file_path, Some(child_parent), symbols);
                }
            }
            return;
        }
    }

    // Recurse into children.
    for i in 0..node.child_count() {
        if let Some(child) = node.child(i) {
            walk_node(child, source, file_path, parent, symbols);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_extract_function_symbol() {
        let source = "fn add(a: i32, b: i32) -> i32 { a + b }";
        let symbols = extract_symbols(source, "test.rs");
        assert_eq!(symbols.len(), 1);
        assert_eq!(symbols[0].name, "add");
        assert_eq!(symbols[0].kind, SymbolKind::Function);
        assert_eq!(symbols[0].line, 1);
    }

    #[test]
    fn test_extract_struct_symbol() {
        let source = "pub struct Foo { x: i32 }";
        let symbols = extract_symbols(source, "test.rs");
        assert!(symbols
            .iter()
            .any(|s| s.name == "Foo" && s.kind == SymbolKind::Struct));
    }

    #[test]
    fn test_extract_rust_symbols() {
        let source = r#"
fn hello() {}
fn world() {}
struct MyStruct { x: i32 }
enum MyEnum { A, B }
trait MyTrait { fn method(&self); }
const MY_CONST: u32 = 42;
"#;
        let symbols = extract_symbols(source, "multi.rs");
        let functions: Vec<_> = symbols
            .iter()
            .filter(|s| s.kind == SymbolKind::Function)
            .collect();
        let structs: Vec<_> = symbols
            .iter()
            .filter(|s| s.kind == SymbolKind::Struct)
            .collect();
        let enums: Vec<_> = symbols
            .iter()
            .filter(|s| s.kind == SymbolKind::Enum)
            .collect();
        let traits: Vec<_> = symbols
            .iter()
            .filter(|s| s.kind == SymbolKind::Trait)
            .collect();
        // hello, world, and method inside trait
        assert!(
            functions.len() >= 2,
            "expected at least 2 functions, got {}",
            functions.len()
        );
        assert_eq!(structs.len(), 1);
        assert_eq!(enums.len(), 1);
        assert_eq!(traits.len(), 1);
    }

    #[test]
    fn test_extract_impl_methods() {
        let source = r#"
struct Foo;
impl Foo {
    fn bar(&self) {}
    fn baz(&self) {}
}
"#;
        let symbols = extract_symbols(source, "impl.rs");
        let methods: Vec<_> = symbols
            .iter()
            .filter(|s| s.kind == SymbolKind::Function && s.parent.is_some())
            .collect();
        assert_eq!(
            methods.len(),
            2,
            "expected 2 methods, got {}",
            methods.len()
        );
        for method in &methods {
            assert_eq!(
                method.parent.as_deref(),
                Some("Foo"),
                "method {} should have parent Foo",
                method.name
            );
        }
        let names: Vec<_> = methods.iter().map(|m| m.name.as_str()).collect();
        assert!(names.contains(&"bar"));
        assert!(names.contains(&"baz"));
    }

    #[test]
    fn test_extract_symbols_from_file() {
        let dir = tempdir().expect("should create temp dir");
        let file_path = dir.path().join("test.rs");
        std::fs::write(
            &file_path,
            "fn greet(name: &str) -> String { name.to_string() }",
        )
        .expect("should write file");
        let symbols = extract_symbols_from_file(&file_path).expect("should extract symbols");
        assert_eq!(symbols.len(), 1);
        assert_eq!(symbols[0].name, "greet");
        assert_eq!(symbols[0].kind, SymbolKind::Function);
    }

    #[test]
    fn test_empty_source_returns_empty() {
        let symbols = extract_symbols("", "empty.rs");
        assert!(symbols.is_empty());
    }
}
